# Generated by Django 2.2.28 on 2023-01-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20230124_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
